"""Initial migration.

Revision ID: f1c21b7d2570
Revises: 
Create Date: 2024-07-24 11:50:16.397816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f1c21b7d2570'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('colaborador',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(length=11), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('ativo', sa.Boolean(), nullable=True),
    sa.Column('data_nascimento', sa.Date(), nullable=False),
    sa.Column('data_admissao', sa.Date(), nullable=False),
    sa.Column('data_rescisao', sa.Date(), nullable=True),
    sa.Column('cargo', sa.String(length=50), nullable=True),
    sa.Column('funcao', sa.String(length=50), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('usuario')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('colaborador')
    # ### end Alembic commands ###
